version: '3.7'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '80:8080'
  # envoy:
  #   image: envoyproxy/envoy:1.23-latest
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
