on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'recap-utr' && github.event_name == 'push' }}
    permissions:
      contents: write
      packages: write
    steps:
      # TODO: qemu
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cihelper/action-semanticrelease-npm@v1
        id: semanticrelease
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: nix run .#dockerManifest --impure
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
